### ISSUE TITLE
Unable to to pass option to bloop script

### ISSUE THREAD

**Issue by leszekgruchala** [scalacenter/bloop#100]
MacOS 10.13.1
Zsh
Bloop version: `66018e0a`
```
➜  some-project git:(feature/some-branch) ✗ bloop projects
Projects loaded from '/Users/lgr/projects/some-project/.bloop-config':
 * core
 * core-test
 * root
 * root-test
 * web
 * web-test

➜  some-project git:(feature/some-branch) ✗ bloop compile -p root
Usage: bloop-ng.py [options] cmd arg1 arg2 ...

bloop-ng.py: error: no such option: -p

➜  some-project git:(feature/some-branch) ✗ bloop compile root
Required option --project / -p not specified

➜  some-project git:(feature/some-branch) ✗ bloop compile --project root
Usage: bloop-ng.py [options] cmd arg1 arg2 ...

bloop-ng.py: error: no such option: --project
```

**Comment by Duhemm** [comment]
I think that `bloop -- compile -p root` should work as a workaround.

**Comment by leszekgruchala** [comment]
That was quick! Thank you, helped.

But another thing, running tests does nothing
```
✗ bloop -- test -p web
✗ bloop -- test -p web-test
```
No output at all. Should I fill another issue?

**Comment by Duhemm** [comment]
Yes please! There are some issues with messages being lost between the server and the client, that could also be the cause. In that case, restarting the server usually helps.

You can also add `--verbose` to test to have bloop show the tests that it discovered.

**Comment by jvican** [comment]
What was the way we decided to solve this issue? Forwarding CLI arguments from the nailgun server to the underlying app?

**Comment by olafurpg** [comment]
I think I fixed this with `alias bloop = ng bloop.Cli` @jvican

**Comment by jvican** [comment]
I have the same alias and this problem still occurs in my machine.

**Comment by Duhemm** [comment]
I have
```sh
alias bloop="~/.bloop/bloop-ng.py bloop.Cli --"
```

And commands such as 
```sh
bloop run -p blabla --args arg0 --args arg1
```

work fine.

**Comment by jvican** [comment]
> alias bloop="~/.bloop/bloop-ng.py bloop.Cli --"
  
The `--` at the end does the trick. However, I wonder if we can fix this in a more fundamental way. I'd like to avoid the need of `--` altogether.

**Comment by jvican** [comment]
`python2 nailgun/pynailgun/ng.py compile -p frontend` should work out of the box with #175. This is more intuitive because what the user can easily assume that the bloop CLI is the equivalent of running the python script `python2 nailgun/pynailgun/ng.py`, without any nailgun-specific implementation detail.

**Comment by jvican** [comment]
Note that, from now on, in case you want to modify one of the nailgun flags (port, server, filearg, show version), you will indeed need to use `--` like `python2 nailgun/pynailgun/ng.py --nailgun-port=1717 -- compile -p frontend` (and this, knowing how CLI parsers work, is intuitive).
  
But the cool thing with #175 is that it won't require you to add `--` for the simplest and most likely use cases.

**Comment by jvican** [comment]
This is already fixed, thanks to all who chimed in. :tada:
