### ISSUE TITLE
Allow `buildTarget/testClasses` after `taskFinish`

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#1067]
BSP clients can make the sensible choice of sending `buildTarget/testClasses` or `buildTarget/mainClasses` BSP requests after they have received `taskFinish` notifications for a given build target. However, Bloop doesn't ensure that the compile products are available until the *whole* compile transaction has been executed. Therefore, there can be race conditions where the clients ask for it before or after the transaction is registered by the bloop compile gatekeeper.

As this behavior doesn't make sense, I'll look into how we can change the internals to ensure fast and reliable results to these BSP requests. /cc @marek1840 who reported this issue and @jastice who might have run into it.

**Comment by jastice** [comment]
Currently in IntelliJ `buildTarget/testClasses` is requested completely independently from compile tasks, afaik. @samvel1024 might know the details. But I agree this behavior makes sense.

**Comment by jvican** [comment]
This is fixed in latest master. @marek1840 I'd love it if you could revert the latest commit to work around this ticket in Metals and confirm it works. It's an important part of the BSP contract Bloop promises to BSP clients and want to confirm there are no surprises.

**Comment by marek1840** [comment]
It seems the issue is still there. After reverting our changes in https://github.com/scalameta/metals/pull/1199 we get some failures:

the only source in the project is:
```scala
package foo
object Main {
  def main(args: Array[String]): Unit = {}
}
```
The logs from metals are:
```
2019-12-19T08:39:06.2391574Z INFO  tests.TestingServer#initialize
2019-12-19T08:39:06.3872068Z INFO  time: generated quick build in 0.15s
2019-12-19T08:39:06.3925825Z INFO  logging to file /home/runner/work/metals/metals/tests/unit/target/e2e/codeLenses/main/.metals/metals.log
2019-12-19T08:39:06.4899249Z INFO  Database: jdbc:h2:file:/home/runner/work/metals/metals/tests/unit/target/e2e/codeLenses/main/.metals/metals (H2 1.4)
2019-12-19T08:39:06.4914816Z INFO  Successfully validated 3 migrations (execution time 00:00.001s)
2019-12-19T08:39:06.4926486Z INFO  Creating Schema History table "PUBLIC"."flyway_schema_history" ...
2019-12-19T08:39:06.4949168Z INFO  Current version of schema "PUBLIC": << Empty Schema >>
2019-12-19T08:39:06.4956930Z INFO  Migrating schema "PUBLIC" to version 1 - Create tables
2019-12-19T08:39:06.4977984Z INFO  Migrating schema "PUBLIC" to version 2 - Server discovery
2019-12-19T08:39:06.4999240Z INFO  Migrating schema "PUBLIC" to version 3 - Jar symbols
2019-12-19T08:39:06.5021596Z INFO  Successfully applied 3 migrations to schema "PUBLIC" (execution time 00:00.008s)
2019-12-19T08:39:06.5992124Z INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/runner/.cache/metals/bsp.trace.json
2019-12-19T08:39:06.6144638Z INFO  Connected to Build server v1.4.0-RC1
2019-12-19T08:39:07.0999058Z INFO  time: indexed workspace in 0.47s
2019-12-19T08:39:07.1017031Z INFO  registered main classes for BuildTargetIdentifier [
2019-12-19T08:39:07.1017422Z   uri = "file:/home/runner/work/metals/metals/tests/unit/target/e2e/codeLenses/main/a/?id=a"
2019-12-19T08:39:07.1017683Z ]: Set()
2019-12-19T08:39:07.1017930Z INFO  registered test classes for BuildTargetIdentifier [
2019-12-19T08:39:07.1018207Z   uri = "file:/home/runner/work/metals/metals/tests/unit/target/e2e/codeLenses/main/a/?id=a"
2019-12-19T08:39:07.1018465Z ]: Set()
2019-12-19T08:39:07.1108837Z INFO  compiling a (1 scala source)
2019-12-19T08:39:07.7022683Z INFO  time: compiled a in 0.59s
2019-12-19T08:39:07.7043227Z INFO  registered main classes for BuildTargetIdentifier [
2019-12-19T08:39:07.7043824Z   uri = "file:/home/runner/work/metals/metals/tests/unit/target/e2e/codeLenses/main/a/?id=a"
2019-12-19T08:39:07.7044189Z ]: Set()
2019-12-19T08:39:07.7044367Z INFO  registered test classes for BuildTargetIdentifier [
2019-12-19T08:39:07.7044513Z   uri = "file:/home/runner/work/metals/metals/tests/unit/target/e2e/codeLenses/main/a/?id=a"
2019-12-19T08:39:07.7045035Z ]: Set()
```

`time: compiled a in 0.59s` log happens on `taskFinish` before asking for `buildTarget/testClasses`, so we can be sure the `taskFinish` was issued from bloop.
`registered ? classes for` tells us there were no test or main classes fetched from bloop.

Could you point me to a test case verifying this issue, so that I can investigate it further?

**Comment by jvican** [comment]
@marek1840 Thanks for looking into this, I'll have a look at this for RC2. I feel this race condition is coming from another place, I need to have a closer look at all of the moving pieces.

**Comment by marek1840** [comment]
Thanks!
