### ISSUE TITLE
homebrew formula should support systems with python3 installed

### ISSUE THREAD

**Issue by easel** [scalacenter/bloop#303]
The install.py script seems to force python 2.7 when home-brew sets it up, but /usr/local/bin/bloop has the standard `#!/usr/bin/env python` at the top, which fails if python3 is installed and set as default (which seems to be happening in the latest home-brew python3 packages).

The ideal would be to detect python 3 and install a python3 friendly version of the script, but the short term workaround is just to replace `python` with `python2.7` in the above, which does work.

**Comment by easel** [comment]
Turns out the relevant fix is already in a PR: 
https://github.com/scalacenter/nailgun/pull/2

**Comment by jvican** [comment]
This is already fixed in latest master, and it's been released as the `1.0.0-M4+8-7b0276a7` development release. It will be accessible in a stable release on Thursday/Friday. Thanks guys for chiming in! :rocket:

**Comment by tpolecat** [comment]
`brew install scalacenter/bloop/bloop` still fails for me. Does the brew formulate need to be updated?
