### ISSUE TITLE
Add python `future` dependency in the brew formula and update docs

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#339]
As we rely on python to install bloop, those who don't have `future` installed will see the following error:
  
```
Traceback (most recent call last):
  File "install.py", line 4, in <module>
    from future import standard_library
ImportError: No module named future
```
  
That can be fixed with `pip2 install future`, `pip3 install future` or `pip install future` depending on which Python version is used. If we add the dependency on the brew formula, OSX users won't need to do that.
  
The rest of users will because we only use a package manager for OSX, so let's document it in the docs. @Duhemm I'm assigning you since you're the overlord of the brew installation :imp:

**Comment by valencik** [comment]
Hopefully solved by https://github.com/scalacenter/bloop/pull/343

**Comment by Duhemm** [comment]
Fixed In #343 by @valencik 🎉

**Comment by jastice** [comment]
Still getting the error (even after manually doing `pip3 install future`). Does the formula or release still need an update?

**Comment by jvican** [comment]
Did you do `pip2 install future`? I think that we need to cut a release for this fix to be in. We're cutting one this afternoon most likely.

**Comment by jastice** [comment]
I didn't have any `pip` or `pip2` available. I'll try againa fter next release
